### ISSUE TITLE
运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子

### ISSUE THREAD

**Issue by JionghaoSong** [duoduoxuexi/yhm#1]

**Comment by duoduoxuexi** [comment]
ok

**Comment by duoduoxuexi** [comment]
我想问一下，那个时间怎么设置会早一点？一般设置到8点多但每天到9点多才会运行

**Comment by JionghaoSong** [comment]
这个没办法，毕竟免费用的github的服务器，是共用的。
你要是想早点，就避开集中时间段，什么整点半点啥的；或者设置的早一点。
最准时的话，建议自己买个云服务器。




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "duoduoxuexi/yhm"                                                                                    ***@***.***&gt;;
Date:&nbsp;Wed, Feb 15, 2023 11:51 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [duoduoxuexi/yhm] 运行成功的话，可以给早安项目(jionghaosong)一个star吗？ 我想凑一个小牌子 (Issue #1)





 
我想问一下，那个时间怎么设置会早一点？一般设置到8点多但每天到9点多才会运行
